name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: |
          npm install
          npm run lint
          npm test

  automerge:
    name: Merge dependabot's PRs
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.github_token }}
